# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-14 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=40)),
                ('total', models.CharField(max_length=10)),
                ('order_date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'ALL'), (1, 'Ordered'), (2, 'Payed'), (3, 'Delivering'), (4, 'Finished'), (5, 'Closed')], default=0)),
                ('paid_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Order_Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=30, null=True)),
                ('img', models.ImageField(default='1.jpg', upload_to='')),
                ('on_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('description_en', models.CharField(max_length=500, null=True)),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'Order_Goods',
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('road', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=40, null=True)),
                ('postcode', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'OrderAddress',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
                ('user_id', models.CharField(max_length=40)),
                ('change_date', models.DateTimeField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'OrderStatusLog',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.OrderAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='user.User'),
        ),
    ]
