# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-19 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191219_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
