# Generated by Django 2.2.1 on 2019-12-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191230_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='on_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='origin_price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
