# Generated by Django 2.2.1 on 2019-12-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191230_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_show',
            field=models.IntegerField(default=1),
        ),
    ]
