# Generated by Django 2.2.1 on 2019-12-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191230_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='super_category_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
